  spring:
    application:
      name: config-server
    cloud:
      config:
        server:
          git:
            uri: https://github.com/liupandeng/SpringCloudLearningAll
  #          search-paths: dev
            username: liupandeng
            password: XXXXXX

  server:
    port: 1201